on:
  push:
    branches:
      - develop
    paths: ['src/**', '.github/workflows/stage-web.yml', 'Dockerfile', 'package.json', 'fly.toml']

env:
  EXPO_PUBLIC_API_BASE_URL: ${{ secrets.EXPO_PUBLIC_API_BASE_URL }}

jobs:
  deploy-backend-stage:
    runs-on: ubuntu-latest
    name: Deploy to stage
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
      - name: Install pnpm
        run: npm install -g pnpm
      - name: pnpm install
        run: pnpm install
      - name: Deploy to stage
        run: |
          ~/.fly/bin/fly deploy \
            --config fly.toml \
            --dockerfile Dockerfile \
            --app culero-stage-web \
            --access-token ${{ secrets.FLY_ACCESS_TOKEN }}
